version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend directory
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Path to your backend directory
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

